<?php

/* 
SELECT s.ID_SESSION, NOM_SESSION, NB_PLACE, COUNT(ID_Stagiaire) AS nbPlacePrises, NB_PLACE -(COUNT(ID_Stagiaire)) AS nbPlaceRestante
FROM SESSION s, STAGIAIRE_SESSION ss
WHERE s.ID_SESSION = ss.ID_SESSION
AND s.ID_SESSION = "6"
GROUP BY NOM_SESSION
 */

